<script lang="ts">
	import { resolve } from '$app/paths';
	import { relayChromeStoreUrl } from '$lib/relay';
	import SpellshapePreview from '$lib/components/SpellshapePreview.svelte';
	import DrawingAnalysisPreview from '$lib/components/DrawingAnalysisPreview.svelte';
</script>
<svelte:head><title>Projects — Structured, Editable AI Work | Stepan Kukharskiy</title><meta name="description" content="Independent projects exploring editable geometry, traceable drawing analysis and reusable AI workflows: Relay, Spellshape / Live OBJ and Drawing Analysis Engine." /><link rel="canonical" href="https://stepankukharskiy.com/projects" /></svelte:head>
<p class="eyebrow">Systems and artifacts</p><h1>Projects</h1><p class="lede">Three independent projects explore the same question: what must an AI-generated result preserve so someone can inspect it, change it and continue the work?</p>
<section id="relay"><h2>Relay</h2><p><strong>Routines → Skills, jobs and retained work.</strong></p><p>Relay turns a useful procedure into work an agent can execute and continue. A Skill holds reusable instructions. A job retains the selected files, artifacts, evidence, assigned checks and exceptions.</p><p>The public Skills are portable. Relay adds coordination and continuation around them.</p><p>The Chrome extension starts with useful text selected in ChatGPT. Choose <strong>Turn into Skill</strong> for a reusable method or <strong>Save work</strong> for a snapshot you can continue later. Review and send the prepared message, then download the result for use in Codex or another AI chat. Relay Desktop is optional.</p><p><strong><a href={relayChromeStoreUrl} rel="external">Get the Chrome extension →</a></strong> · <a href={resolve('/relay/chrome')}>How it works</a></p><p><a href="https://task-relay-website-production.up.railway.app">Relay website →</a> · <a href="https://task-relay-website-production.up.railway.app/skills">Downloadable Skills</a> · <a href="https://github.com/StepanKukharskiy/task-relay">Source</a></p></section>
<section id="live-obj"><h2>Spellshape / Live OBJ</h2><SpellshapePreview /><p><strong>Intent → portable, editable geometry.</strong></p><p>Spellshape is an AI-native authoring environment built around Live OBJ. The artifact combines standard OBJ geometry with <code>#@</code> metadata describing semantic parts, parameters and procedural intent. Ordinary OBJ readers can use the geometry; tools that understand the metadata can continue editing the scene.</p><p>The mesh cache travels with the structure that explains how it can change. Metadata-driven editability depends on the capabilities of the consuming tool.</p><p><a href="https://spellshape.com">Spellshape website →</a> · <a href="https://github.com/StepanKukharskiy/live-obj">Live OBJ source and format</a></p></section>
<section id="drawing-engine"><h2>Drawing Analysis Engine</h2><DrawingAnalysisPreview /><p><strong>Drawing evidence → inspectable analysis.</strong></p><p>A callable PDF drawing-understanding engine. Drawing evidence, declared schedule values, calculated results and engineer approval remain separate. A saved project preserves the source PDF, marked audit PDF, SQLite state and a hashed results index. Unresolved geometry and unsupported exports retain explicit reasons.</p><p>The analysis stays tied to its evidence. Running the engine or exporting geometry does not grant engineer approval.</p><p><a href="https://github.com/StepanKukharskiy/drawing-analysis-engine">Engine source and documentation →</a></p></section>
<section><h2>How they can work together</h2><p>A Skill can expose a callable engine or script to an agent. That creates a way to combine drawing analysis, editable 3D, reports and downstream jobs while each project keeps its own scope.</p><p>These are integration directions to test. This page does not claim that Relay already ships an end-to-end drawing or Live OBJ workflow.</p><p><a href={resolve('/ai-work')}>Follow the practical experiments →</a></p></section>
